title: "homestead"
email: matheus.g.moreli@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  by kunshire
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://purelog.netlify.app" # the base hostname & protocol for your site, e.g. http://example.com
repository: 
twitter: 
github: graminha-matheus

header_image: assets/me-removebg-preview(4).png
google_analytics:
comments: false
disqus: 

author: Kunshire
author_bio: >-
  Hey there! 😄 My name is Matheus Graminha, i go by the nickname Kunshire. I'm a 20-year-old São Paulo cybersecurity analyst. 
  This blog is mostly a place for my writeups, news that i find interesting, or for dumping content.
  Feel free to contact me on my email! matheus.g.moreli@pm.me
author_pic: assets/me-removebg-preview(4).png
paginate: 4
paginate_path: "/:num/"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
permalink: /:title

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: Brennan K. Brown
      avatar: assets/profile-sm.png
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
  - scope:
      path: ""
      type: journals
    values:
      layout: journal-entry
      content-type: journals

# Allows all pages to be put into `_pages` folder
# for easier navigation and better SEO.
collections:
  pages:
    output: true
    permalink: /:title
  notes:
    output: true
    permalink: /notes/:title
  journals:
    output: true
    permalink: /journals/:title

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
